name: Build and Test

on:
  push:
    branches: [ DEV, Master ]
  pull_request:
    branches: [ DEV, Master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: ğŸ“¥ Checkout repository (SOLTEC.Core)
      uses: actions/checkout@v3

    - name: ğŸ§° Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: ğŸ“¦ Restore dependencies
      run: dotnet restore

    - name: ğŸ§ª Run NUnit tests
      run: dotnet test ./Tests/SOLTEC.Core.Tests.NuNit/SOLTEC.Core.Tests.NuNit.csproj --no-build --verbosity normal

    - name: ğŸ§ª Run xUnit tests
      run: dotnet test ./Tests/SOLTEC.Core.Tests.xUnit/SOLTEC.Core.Tests.xUnit.csproj --no-build --verbosity normal

    - name: ğŸ—ï¸ Build project
      run: dotnet build ./SOLTEC.Core/SOLTEC.Core.csproj --no-restore --configuration Release
